

# This file was *autogenerated* from the file range_uvrs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_20 = Integer(20); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_19 = Integer(19)

Ta = Matrix([[_sage_const_1 , _sage_const_0 ],[_sage_const_0 , _sage_const_1 /_sage_const_2 ]])
Tb = Matrix([[_sage_const_1 , _sage_const_0 ],[_sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_2 ]])
Tc = Matrix([[_sage_const_0 , _sage_const_1 ],[-_sage_const_1 /_sage_const_2 , _sage_const_1 /_sage_const_2 ]])
I = Matrix([[-_sage_const_2 **_sage_const_20 , _sage_const_0 ],[_sage_const_0 , -_sage_const_2 **_sage_const_20 ]])


def Mgen(i=_sage_const_3 ):
    Ms = [[I]]
    for i in range(i):
        tmp = [T*M for T in [Ta, Tb, Tc] for M in Ms[-_sage_const_1 ]]
        Ms.append(tmp)

    return Ms
Ms = Mgen(_sage_const_8 )


print("hello")
print(Ms[_sage_const_0 ])
print("hello")
for i in Ms[_sage_const_1 ]:
    print(i)
    print()

##### Bounds

u_low = -_sage_const_2 **_sage_const_20 



##### verification

Us_min = [min([matrix[_sage_const_0 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
Us_max = [max([matrix[_sage_const_0 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]

Vs_min = [min([matrix[_sage_const_0 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
Vs_max = [max([matrix[_sage_const_0 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]

Rs_min = [min([matrix[_sage_const_1 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
Rs_max = [max([matrix[_sage_const_1 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]

Ss_min = [min([matrix[_sage_const_1 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
Ss_max = [max([matrix[_sage_const_1 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]

RmUs_min = [min([matrix[_sage_const_1 ][_sage_const_0 ] - matrix[_sage_const_0 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
RmUs_max = [max([matrix[_sage_const_1 ][_sage_const_0 ] - matrix[_sage_const_0 ][_sage_const_0 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]

SmVs_min = [min([matrix[_sage_const_1 ][_sage_const_1 ] - matrix[_sage_const_0 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]
SmVs_max = [max([matrix[_sage_const_1 ][_sage_const_1 ] - matrix[_sage_const_0 ][_sage_const_1 ] for matrix in Ms[i]]) for i in range(_sage_const_1 ,_sage_const_8 )]



print(Us_min)

for i, num in enumerate(Us_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_19 

for i, num in enumerate(Us_min, _sage_const_1 ):
    assert num >= -_sage_const_2 **_sage_const_20 

for i, num in enumerate(Vs_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_19  - (_sage_const_2 **(_sage_const_20  - i))

for i, num in enumerate(Vs_min, _sage_const_1 ):
    assert num >= -_sage_const_2 **_sage_const_20 

for i, num in enumerate(Rs_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_19 

for i, num in enumerate(Rs_min, _sage_const_1 ):
    assert num >= _sage_const_2 **(_sage_const_20 -i) - _sage_const_2 **_sage_const_20 

for i, num in enumerate(Ss_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_19  - (_sage_const_2 **(_sage_const_20  - i))

for i, num in enumerate(Ss_min, _sage_const_1 ):
    assert num >= _sage_const_2 **(_sage_const_20 -i) - _sage_const_2 **_sage_const_20 

for i, num in enumerate(RmUs_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_20 

for i, num in enumerate(RmUs_min, _sage_const_1 ):
    assert num >= _sage_const_2 **(_sage_const_20 -i) - _sage_const_2 **_sage_const_19 

for i, num in enumerate(SmVs_max, _sage_const_1 ):
    assert num <= _sage_const_2 **_sage_const_20  - _sage_const_2 **(_sage_const_20 -i)

for i, num in enumerate(SmVs_min, _sage_const_1 ):
    assert num >= - _sage_const_2 **_sage_const_19 

